//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workull
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskComment
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Text { get; set; }
        public int TaskId { get; set; }
        public int AuthorId { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Task Task { get; set; }
    }
}
